kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: database-persistent-volume-claim
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes: [ReadWriteOnce] # alternatives: ReadWriteMany, ReadOnlyMany, and more
  resources:
    requests:
      storage: 5Gi
  # storageClassName: standard <-- this is the default. you can check your storage options via 'kubectl get storageclass' and 'kubectl describe storageclass'