apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce # alternatives: ReadWriteMany, ReadOnlyMany, and more
  resources:
    requests:
      storage: 2Gi
  # storageClassName: standard <-- this is the default. you can check your storage options via 'kubectl get storageclass' and 'kubectl describe storageclass'