apiVersion: extensions/v1beta1 # networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations: # configuration rules here
    kubernetes.io/ingress.class: nginx # this tells kubernetes that we want to create an ingress controller based on the 'k8s nginx ingress project'
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1 # configures how our copy of nginx behaves (in this case, it will rewrite the inbound path to just / . for example - if inbound path is /api, then nginx will rewrite it to just /)
spec: 
  rules:
    - http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: client-cluster-ip-service
              servicePort: 3000
          - path: /api/?(.*)
            backend:
              serviceName: server-cluster-ip-service
              servicePort: 5000